suppressPackageStartupMessages({
  library(devtools)
  library(rmarkdown)
  library(bambu)
  library(data.table)
  library(dplyr)
  library(tidyr)
  library(readr)
  library(tibble)
  library(purrr)
  library(forcats)
  library(GenomicFeatures)
  library(Biostrings)
  library(shinyjs)
  library(shiny)
  library(shinythemes)
  library(shinydashboard)
  library(ORFik)
  library(GenomicRanges)
  library(rtracklayer)
  library(markdown)
  library(devtools)
  library(vsn)
  library(ggtranscript)
  library(patchwork)
  library(ggrepel)
  library(optparse)
  library(mygene)
  library(tximport)
})

options(shiny.maxRequestSize = 21474836480) # 20GB

options(scipen=999)

source("R/integration_functions.R")
source("R/visualisation_function.R")
source("R/run_bambu_function.R")

